// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXv1b5eS4ag27aImKa-xhFE2gakAd_pX4',
    appId: '1:1022130965696:web:a26a65b6865d10e10a3125',
    messagingSenderId: '1022130965696',
    projectId: 'eden-237a9',
    authDomain: 'eden-237a9.firebaseapp.com',
    storageBucket: 'eden-237a9.firebasestorage.app',
    measurementId: 'G-E3ZS67N713',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gaq7FKSVM4VtTtmd276kJ76GPHzHfZs',
    appId: '1:1022130965696:android:cf14421bc69384170a3125',
    messagingSenderId: '1022130965696',
    projectId: 'eden-237a9',
    storageBucket: 'eden-237a9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu1RjAmpOtfzumYzw6VDYMNL5xqI1G4g4',
    appId: '1:1022130965696:ios:3bb1a9e3c4fb451c0a3125',
    messagingSenderId: '1022130965696',
    projectId: 'eden-237a9',
    storageBucket: 'eden-237a9.firebasestorage.app',
    androidClientId: '1022130965696-difh6rigu4msgeib5e5tg9v392clvdfe.apps.googleusercontent.com',
    iosClientId: '1022130965696-ugehe2paj92it0vuhi48o68cn0190a7h.apps.googleusercontent.com',
    iosBundleId: 'com.edenmvp.companionApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu1RjAmpOtfzumYzw6VDYMNL5xqI1G4g4',
    appId: '1:1022130965696:ios:3bb1a9e3c4fb451c0a3125',
    messagingSenderId: '1022130965696',
    projectId: 'eden-237a9',
    storageBucket: 'eden-237a9.firebasestorage.app',
    androidClientId: '1022130965696-difh6rigu4msgeib5e5tg9v392clvdfe.apps.googleusercontent.com',
    iosClientId: '1022130965696-ugehe2paj92it0vuhi48o68cn0190a7h.apps.googleusercontent.com',
    iosBundleId: 'com.edenmvp.companionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXv1b5eS4ag27aImKa-xhFE2gakAd_pX4',
    appId: '1:1022130965696:web:ab968b49ac70244a0a3125',
    messagingSenderId: '1022130965696',
    projectId: 'eden-237a9',
    authDomain: 'eden-237a9.firebaseapp.com',
    storageBucket: 'eden-237a9.firebasestorage.app',
    measurementId: 'G-TH97E243P7',
  );
}
